In [70]:
import pandas, sqlite3

def show_invidiual_schedule(student_id: str | int):
  with sqlite3.connect("database.db") as conn:
    records = [*conn.cursor().execute(f"""
      SELECT en.student_id, en.section_code, se.course_code, co.course_name, s.day, s.slot
      FROM enrolments en
      JOIN sections se ON en.section_code = se.section_code
      JOIN courses co ON se.course_code = co.course_code
      JOIN schedule s ON s.course_code = co.course_code
      WHERE en.student_id = {student_id}
      ORDER BY s.day, s.slot
    """)]
  return pandas.DataFrame(records, columns=["Mã SV", "Mã LMH", "Mã MH", "Tên MH", "Ngày thi", "Ca thi"])

In [71]:
show_invidiual_schedule(24021400)

,Mã SV,Mã LMH,Mã MH,Tên MH,Ngày thi,Ca thi
0,24021400,INT2211 11,INT2211,Cơ sở dữ liệu,5,0
1,24021400,INT2212 8,INT2212,Kiến trúc máy tính,10,3
2,24021400,INT3405E 2,INT3405E,Học máy,14,0
3,24021400,THL1057 1,THL1057,Nhà nước và pháp luật đại cương,17,1
4,24021400,INT 3103 2,INT3103,Tối ưu hóa,22,2
5,24021400,INT2044E 2,INT2044E,Lý thuyết thông tin,23,3

In [72]:
show_invidiual_schedule(24021876)

,Mã SV,Mã LMH,Mã MH,Tên MH,Ngày thi,Ca thi
0,24021876,INT2210 70,INT2210,Cấu trúc dữ liệu và giải thuật,2,3
1,24021876,POL1001 51,POL1001,Tư tưởng Hồ Chí Minh,3,1
2,24021876,FLF1108 59,FLF1108,Tiếng Anh B2,4,1
3,24021876,ELT2035 49,ELT2035,Tín hiệu và hệ thống,9,1
4,24021876,ELT 2032 51,ELT2032,Linh kiện điện tử,12,0
5,24021876,MAT1101 3,MAT1101,Xác suất thống kê,15,2
6,24021876,HIS1001 42,HIS1001,Lịch sử Đảng Cộng sản Việt Nam,21,3
7,24021876,INT 3103 2,INT3103,Tối ưu hóa,22,2